# SQLite version 3.x

development:
  adapter: postgresql
  encoding: utf8
  database: fuzzybear_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: fuzzybear_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: fuzzybear_production
  pool: 5
  password:
